'use client'
import {useEffect,useState} from 'react'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1'
export default function Home(){const [token,setToken]=useState(''); const [tab,setTab]=useState('Dashboard'); const [data,setData]=useState<any>(null); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
async function login(e:any){e.preventDefault();setError('');let r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});let j=await r.json();if(!r.ok){setError(j.detail||'Login failed');return}localStorage.setItem('token',j.access_token);setToken(j.access_token)}
async function load(path:string){let r=await fetch(API+path,{headers:{Authorization:`Bearer ${token}`}});let j=await r.json();setData(j)}
useEffect(()=>{const t=localStorage.getItem('token');if(t)setToken(t)},[]);useEffect(()=>{if(token){if(tab==='Dashboard')load('/analytics/summary?days=7');if(tab==='AI Agents')load('/agents');if(tab==='Calls')load('/calls');if(tab==='Contacts')load('/contacts');if(tab==='Appointments')load('/appointments');if(tab==='Campaigns')load('/campaigns')}},[token,tab]);
if(!token)return <main className="login"><div className="card"><div className="eyebrow">AI VOICE EMPLOYEE</div><h1>Give your business a voice.</h1><p>Production-oriented AI calling platform for inbound and authorized outbound conversations.</p><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" type="password"/><button>Sign in</button></form><small>{error||'Use your configured tenant account.'}</small></div></main>
const nav=['Dashboard','AI Agents','Phone Numbers','Calls','Contacts','Campaigns','Appointments','Knowledge','Human Agents','Analytics','Billing','Team','Audit Logs','Settings']; return <div className="app"><aside><div className="brand">◉ VoiceOS</div>{nav.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button onClick={()=>{localStorage.removeItem('token');setToken('')}} className="logout">Sign out</button></aside><main className="content"><header><div><div className="eyebrow">WORKSPACE</div><h1>{tab}</h1></div><span className="pill">Production foundation</span></header>{tab==='Dashboard'?<><section className="hero"><div><h2>Your AI employees are ready to work.</h2><p>Connect a Twilio number, publish an agent, and the realtime voice pipeline can answer calls.</p></div><div className="hero-stat"><b>{data?.total_calls??0}</b><span>calls · last 7 days</span></div></section><div className="grid">{[['Answered',data?.answered??0],['Completed',data?.completed??0],['Avg duration',`${Math.round(data?.average_duration_seconds??0)}s`],['Transfer rate',`${Math.round((data?.transfer_rate??0)*100)}%`]].map(([a,b])=><div className="metric" key={a as string}><span>{a}</span><strong>{b}</strong></div>)}</div></>:<section className="data card"><pre>{JSON.stringify(data,null,2)}</pre></section>}</main></div>}
