import uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,ForeignKey,Integer,String,Text,UniqueConstraint,JSON,Float
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped,mapped_column
from app.db.base import Base
def uid():return uuid.uuid4()
def utcnow():return datetime.now(timezone.utc)
class TS:
    created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,nullable=False)
    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=utcnow,onupdate=utcnow,nullable=False)
class Tenant(TS,Base):
    __tablename__='tenants';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(200));active:Mapped[bool]=mapped_column(Boolean,default=True)
class TenantSetting(TS,Base):
    __tablename__='tenant_settings';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'),unique=True);settings:Mapped[dict]=mapped_column(JSON,default=dict)
class Role(Base):
    __tablename__='roles';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(50),unique=True)
class Permission(Base):
    __tablename__='permissions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(100),unique=True)
class User(TS,Base):
    __tablename__='users';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'));email:Mapped[str]=mapped_column(String(320),unique=True,index=True);password_hash:Mapped[str]=mapped_column(String(255));role:Mapped[str]=mapped_column(String(50),default='TENANT_OWNER');active:Mapped[bool]=mapped_column(Boolean,default=True);email_verified:Mapped[bool]=mapped_column(Boolean,default=False)
class Session(TS,Base):
    __tablename__='sessions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);user_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'));token_hash:Mapped[str]=mapped_column(String(128),unique=True);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Agent(TS,Base):
    __tablename__='agents';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'));name:Mapped[str]=mapped_column(String(200));description:Mapped[str|None]=mapped_column(Text);active_version_id:Mapped[uuid.UUID|None]=mapped_column(UUID(as_uuid=True));active:Mapped[bool]=mapped_column(Boolean,default=True)
class AgentVersion(TS,Base):
    __tablename__='agent_versions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'));agent_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('agents.id',ondelete='CASCADE'));version:Mapped[int]=mapped_column(Integer);status:Mapped[str]=mapped_column(String(20),default='DRAFT');greeting:Mapped[str]=mapped_column(Text,default='Hello! How can I help you today?');system_instructions:Mapped[str]=mapped_column(Text,default='Be helpful, truthful and concise.');voice:Mapped[str]=mapped_column(String(50),default='marin');language:Mapped[str]=mapped_column(String(10),default='en');personality:Mapped[str]=mapped_column(Text,default='professional, warm');business_context:Mapped[str|None]=mapped_column(Text);objectives:Mapped[list]=mapped_column(JSON,default=list);transfer_rules:Mapped[dict]=mapped_column(JSON,default=dict);compliance:Mapped[dict]=mapped_column(JSON,default=dict);__table_args__=(UniqueConstraint('agent_id','version',name='uq_agent_version'),)
class PhoneNumber(TS,Base):
    __tablename__='phone_numbers';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'));e164:Mapped[str]=mapped_column(String(32));provider:Mapped[str]=mapped_column(String(30),default='twilio');provider_number_id:Mapped[str|None]=mapped_column(String(100));agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('agents.id'));country:Mapped[str|None]=mapped_column(String(4));capabilities:Mapped[dict]=mapped_column(JSON,default=dict);active:Mapped[bool]=mapped_column(Boolean,default=True)
class Contact(TS,Base):
    __tablename__='contacts';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id',ondelete='CASCADE'));first_name:Mapped[str|None]=mapped_column(String(100));last_name:Mapped[str|None]=mapped_column(String(100));phone:Mapped[str|None]=mapped_column(String(32));email:Mapped[str|None]=mapped_column(String(320));tags:Mapped[list]=mapped_column(JSON,default=list);custom_fields:Mapped[dict]=mapped_column(JSON,default=dict);status:Mapped[str]=mapped_column(String(30),default='ACTIVE')
class ContactConsent(TS,Base):
    __tablename__='contact_consents';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));contact_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('contacts.id'));channel:Mapped[str]=mapped_column(String(30));type:Mapped[str]=mapped_column(String(50));source:Mapped[str|None]=mapped_column(String(100));status:Mapped[str]=mapped_column(String(30),default='UNKNOWN');revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Call(TS,Base):
    __tablename__='calls';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));agent_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('agents.id'));agent_version_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('agent_versions.id'));phone_number_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('phone_numbers.id'));contact_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('contacts.id'));provider_call_id:Mapped[str|None]=mapped_column(String(100),index=True);provider_stream_id:Mapped[str|None]=mapped_column(String(100));direction:Mapped[str]=mapped_column(String(20));from_number:Mapped[str|None]=mapped_column(String(32));to_number:Mapped[str|None]=mapped_column(String(32));status:Mapped[str]=mapped_column(String(30),default='CREATED');outcome:Mapped[str|None]=mapped_column(String(100));duration_seconds:Mapped[int|None]=mapped_column(Integer);ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));recording_url:Mapped[str|None]=mapped_column(Text);usage:Mapped[dict]=mapped_column(JSON,default=dict);cost:Mapped[float|None]=mapped_column(Float)
class CallEvent(TS,Base):
    __tablename__='call_events';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));call_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('calls.id'));event_type:Mapped[str]=mapped_column(String(80));payload:Mapped[dict]=mapped_column(JSON,default=dict)
class Transcript(TS,Base):
    __tablename__='transcripts';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));call_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('calls.id'),unique=True);language:Mapped[str|None]=mapped_column(String(10));status:Mapped[str]=mapped_column(String(30),default='PROCESSING')
class TranscriptSegment(Base):
    __tablename__='transcript_segments';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));transcript_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('transcripts.id'));speaker:Mapped[str]=mapped_column(String(30));text:Mapped[str]=mapped_column(Text);started_at:Mapped[float|None]=mapped_column(Float);ended_at:Mapped[float|None]=mapped_column(Float);confidence:Mapped[float|None]=mapped_column(Float)
class CallSummary(TS,Base):
    __tablename__='call_summaries';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));call_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('calls.id'),unique=True);summary:Mapped[str]=mapped_column(Text);intent:Mapped[str|None]=mapped_column(String(100));outcome:Mapped[str|None]=mapped_column(String(100));sentiment:Mapped[str|None]=mapped_column(String(30));follow_up_required:Mapped[bool]=mapped_column(Boolean,default=False);next_action:Mapped[str|None]=mapped_column(Text)
class KnowledgeSource(TS,Base):
    __tablename__='knowledge_sources';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(200));source_type:Mapped[str]=mapped_column(String(30));config:Mapped[dict]=mapped_column(JSON,default=dict)
class KnowledgeDocument(TS,Base):
    __tablename__='knowledge_documents';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));source_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('knowledge_sources.id'));title:Mapped[str]=mapped_column(String(300));content:Mapped[str]=mapped_column(Text);status:Mapped[str]=mapped_column(String(30),default='READY')
class KnowledgeChunk(Base):
    __tablename__='knowledge_chunks';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));document_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('knowledge_documents.id'));content:Mapped[str]=mapped_column(Text);chunk_index:Mapped[int]=mapped_column(Integer)
class ToolDefinition(TS,Base):
    __tablename__='tool_definitions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(100));description:Mapped[str]=mapped_column(Text);schema:Mapped[dict]=mapped_column(JSON);enabled:Mapped[bool]=mapped_column(Boolean,default=True)
class ToolPermission(Base):
    __tablename__='tool_permissions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));tool_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tool_definitions.id'));agent_version_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('agent_versions.id'));enabled:Mapped[bool]=mapped_column(Boolean,default=True)
class Appointment(TS,Base):
    __tablename__='appointments';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));contact_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('contacts.id'));start_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));end_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));timezone:Mapped[str]=mapped_column(String(64));status:Mapped[str]=mapped_column(String(30),default='BOOKED');resource:Mapped[str|None]=mapped_column(String(100));location:Mapped[str|None]=mapped_column(Text);meeting_url:Mapped[str|None]=mapped_column(Text);notes:Mapped[str|None]=mapped_column(Text)
class Lead(TS,Base):
    __tablename__='leads';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));contact_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('contacts.id'));source:Mapped[str|None]=mapped_column(String(100));stage:Mapped[str]=mapped_column(String(50),default='NEW');notes:Mapped[str|None]=mapped_column(Text)
class Campaign(TS,Base):
    __tablename__='campaigns';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(200));status:Mapped[str]=mapped_column(String(30),default='DRAFT');schedule:Mapped[dict]=mapped_column(JSON,default=dict);retry_policy:Mapped[dict]=mapped_column(JSON,default=dict);concurrency:Mapped[int]=mapped_column(Integer,default=1)
class CampaignContact(Base):
    __tablename__='campaign_contacts';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));campaign_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('campaigns.id'));contact_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('contacts.id'));state:Mapped[str]=mapped_column(String(30),default='QUEUED');attempts:Mapped[int]=mapped_column(Integer,default=0)
class CampaignAttempt(TS,Base):
    __tablename__='campaign_attempts';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));campaign_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('campaigns.id'));contact_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('contacts.id'));call_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('calls.id'));state:Mapped[str]=mapped_column(String(30));error_code:Mapped[str|None]=mapped_column(String(100))
class HumanAgent(TS,Base):
    __tablename__='human_agents';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(150));phone:Mapped[str]=mapped_column(String(32));status:Mapped[str]=mapped_column(String(20),default='OFFLINE');priority:Mapped[int]=mapped_column(Integer,default=0);department:Mapped[str|None]=mapped_column(String(100))
class RoutingGroup(TS,Base):
    __tablename__='routing_groups';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(150));strategy:Mapped[str]=mapped_column(String(30),default='ROUND_ROBIN')
class TransferDestination(TS,Base):
    __tablename__='transfer_destinations';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(150));phone:Mapped[str]=mapped_column(String(32));routing_group_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('routing_groups.id'))
class BusinessHours(TS,Base):
    __tablename__='business_hours';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'),unique=True);timezone:Mapped[str]=mapped_column(String(64),default='Asia/Kolkata');hours:Mapped[dict]=mapped_column(JSON,default=dict)
class CompliancePolicy(TS,Base):
    __tablename__='compliance_policies';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'),unique=True);policy:Mapped[dict]=mapped_column(JSON,default=dict)
class Plan(Base):
    __tablename__='plans';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(100),unique=True);limits:Mapped[dict]=mapped_column(JSON,default=dict);stripe_price_id:Mapped[str|None]=mapped_column(String(100))
class Subscription(TS,Base):
    __tablename__='subscriptions';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'),unique=True);plan_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('plans.id'));stripe_customer_id:Mapped[str|None]=mapped_column(String(100));stripe_subscription_id:Mapped[str|None]=mapped_column(String(100));status:Mapped[str]=mapped_column(String(30),default='TRIALING')
class UsageRecord(TS,Base):
    __tablename__='usage_records';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));metric:Mapped[str]=mapped_column(String(50));quantity:Mapped[float]=mapped_column(Float);period_start:Mapped[datetime]=mapped_column(DateTime(timezone=True));period_end:Mapped[datetime]=mapped_column(DateTime(timezone=True))
class ApiKey(TS,Base):
    __tablename__='api_keys';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID]=mapped_column(ForeignKey('tenants.id'));name:Mapped[str]=mapped_column(String(100));secret_hash:Mapped[str]=mapped_column(String(128),unique=True);scopes:Mapped[list]=mapped_column(JSON,default=list);expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class AuditLog(TS,Base):
    __tablename__='audit_logs';id:Mapped[uuid.UUID]=mapped_column(UUID(as_uuid=True),primary_key=True,default=uid);tenant_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('tenants.id'));user_id:Mapped[uuid.UUID|None]=mapped_column(ForeignKey('users.id'));action:Mapped[str]=mapped_column(String(100));resource_type:Mapped[str|None]=mapped_column(String(50));resource_id:Mapped[str|None]=mapped_column(String(100));metadata_:Mapped[dict]=mapped_column('metadata',JSON,default=dict)
