'use client'
import {useEffect,useState} from 'react'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1'
type Call={id:string;contact_id:string|null;phone_number_id:string|null;direction:string;from_number:string|null;to_number:string|null;status:string;outcome:string|null;duration_seconds:number|null;provider_call_id:string|null;created_at:string}
export default function CallsConsole(){
 const [token,setToken]=useState(''); const [calls,setCalls]=useState<Call[]>([]); const [summary,setSummary]=useState<any>({}); const [status,setStatus]=useState(''); const [direction,setDirection]=useState(''); const [error,setError]=useState('');
 async function load(){if(!token)return; const qs=new URLSearchParams(); if(status)qs.set('status',status); if(direction)qs.set('direction',direction); const [a,b]=await Promise.all([fetch(`${API}/calls?${qs}`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/calls/summary`,{headers:{Authorization:`Bearer ${token}`}})]); const aj=await a.json(); const bj=await b.json(); if(!a.ok){setError(aj.detail||'Unable to load calls');return} setCalls(aj);setSummary(bj)}
 useEffect(()=>{const t=localStorage.getItem('token');if(t)setToken(t)},[]); useEffect(()=>{load()},[token,status,direction])
 return <main style={{padding:32,maxWidth:1200,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:24}}><div><div style={{fontSize:12,letterSpacing:2}}>VOICEOS</div><h1>Calling Console</h1><p>Monitor active and historical AI calls.</p></div><button onClick={load}>Refresh</button></div>{error&&<div style={{padding:12,marginBottom:16}}>{error}</div>}<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:24}}>{[['Total',summary.total||0],['Active',summary.active||0],['Completed',summary.completed||0],['Failed',summary.failed||0]].map(([k,v])=><div key={k as string} style={{border:'1px solid #ddd',borderRadius:10,padding:16}}><small>{k}</small><h2>{v}</h2></div>)}</div><div style={{display:'flex',gap:10,marginBottom:16}}><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>QUEUED</option><option>RINGING</option><option>IN_PROGRESS</option><option>COMPLETED</option><option>FAILED</option><option>NO_ANSWER</option><option>BUSY</option></select><select value={direction} onChange={e=>setDirection(e.target.value)}><option value="">All directions</option><option>INBOUND</option><option>OUTBOUND</option></select></div><section style={{border:'1px solid #ddd',borderRadius:12,overflow:'hidden'}}>{calls.length===0?<p style={{padding:20}}>No calls found.</p>:calls.map(c=><div key={c.id} style={{padding:16,borderBottom:'1px solid #eee',display:'grid',gridTemplateColumns:'1.2fr .8fr .8fr 1fr',gap:12,alignItems:'center'}}><div><strong>{c.to_number||c.from_number||'Unknown number'}</strong><div><small>{c.direction} · {new Date(c.created_at).toLocaleString()}</small></div></div><span>{c.status}</span><span>{c.duration_seconds!=null?`${c.duration_seconds}s`:'—'}</span><span>{c.outcome||c.provider_call_id||'—'}</span></div>)}</section></main>
}
