'use client'
import {useEffect,useState} from 'react'
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api/v1'
type Campaign={id:string;name:string;status:string;schedule:Record<string,unknown>;retry_policy:Record<string,unknown>;concurrency:number}
type Contact={id:string;first_name:string|null;last_name:string|null;phone:string|null;status:string}
type Phone={id:string;e164:string;active:boolean;outbound_enabled:boolean}
export default function Campaigns(){
 const [token,setToken]=useState(''); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [contacts,setContacts]=useState<Contact[]>([]); const [phones,setPhones]=useState<Phone[]>([]); const [selected,setSelected]=useState<Campaign|null>(null); const [campaignContacts,setCampaignContacts]=useState<string[]>([]); const [stats,setStats]=useState<any>(null); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [concurrency,setConcurrency]=useState(1); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{const t=localStorage.getItem('token');if(t)setToken(t)},[])
 async function req(path:string,init?:RequestInit){const r=await fetch(API+path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers||{})}});const j=await r.json().catch(()=>null);if(!r.ok)throw Error(j?.detail||'Request failed');return j}
 async function load(){try{const [c,co,p]=await Promise.all([req('/campaigns'),req('/contacts?limit=200'),req('/phone-numbers')]);setCampaigns(c);setContacts(co);setPhones(p);if(selected)await selectCampaign(selected.id)}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(token)load()},[token])
 async function selectCampaign(id:string){try{const c=await req(`/campaigns/${id}`);setSelected(c);const cc=await req(`/campaigns/${id}/contacts`);setCampaignContacts(cc.map((x:any)=>x.contact_id));setStats(await req(`/campaigns/${id}/stats`))}catch(e:any){setError(e.message)}}
 async function create(){try{const c=await req('/campaigns',{method:'POST',body:JSON.stringify({name,phone_number_id:phone,schedule:{},retry_policy:{max_attempts:3},concurrency})});setName('');await load();await selectCampaign(c.id);setMessage('Campaign created.')}catch(e:any){setError(e.message)}}
 async function addContact(id:string){if(!selected)return;try{await req(`/campaigns/${selected.id}/contacts`,{method:'POST',body:JSON.stringify({contact_ids:[id]})});await selectCampaign(selected.id);setMessage('Contact added.')}catch(e:any){setError(e.message)}}
 async function action(a:'start'|'pause'|'resume'){if(!selected)return;try{const c=await req(`/campaigns/${selected.id}/${a}`,{method:'POST'});setSelected(c);await selectCampaign(c.id);setMessage(`Campaign ${a}ed.`)}catch(e:any){setError(e.message)}}
 if(!token)return <main style={{padding:40}}>Sign in from the main dashboard first.</main>
 return <main style={{padding:32,maxWidth:1200,margin:'0 auto'}}><h1>Campaigns</h1><p>Create and operate authorized outbound calling campaigns.</p>{message&&<div className="card">{message}</div>}{error&&<div className="card">{error}</div>}
 <section className="card"><h2>New campaign</h2><div style={{display:'grid',gridTemplateColumns:'2fr 2fr 1fr auto',gap:10}}><input placeholder="Campaign name" value={name} onChange={e=>setName(e.target.value)}/><select value={phone} onChange={e=>setPhone(e.target.value)}><option value="">Select phone</option>{phones.filter(p=>p.active&&p.outbound_enabled).map(p=><option key={p.id} value={p.id}>{p.e164}</option>)}</select><input type="number" min={1} max={50} value={concurrency} onChange={e=>setConcurrency(Number(e.target.value))}/><button disabled={!name||!phone} onClick={create}>Create</button></div></section>
 <section style={{display:'grid',gridTemplateColumns:'1fr 2fr',gap:20,marginTop:20}}><div className="card"><h2>Campaigns</h2>{campaigns.map(c=><button key={c.id} onClick={()=>selectCampaign(c.id)} style={{display:'block',width:'100%',textAlign:'left',padding:12,marginBottom:8}}><strong>{c.name}</strong><br/><small>{c.status} · concurrency {c.concurrency}</small></button>)}{!campaigns.length&&<p>No campaigns yet.</p>}</div>
 <div className="card">{selected?<><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><h2>{selected.name}</h2><p>Status: <strong>{selected.status}</strong></p></div><div>{selected.status==='DRAFT'&&<button onClick={()=>action('start')}>Start</button>} {selected.status==='ACTIVE'&&<button onClick={()=>action('pause')}>Pause</button>} {selected.status==='PAUSED'&&<button onClick={()=>action('resume')}>Resume</button>}</div></div><div className="grid">{[['Total',stats?.total],['Queued',stats?.queued],['In progress',stats?.in_progress],['Completed',stats?.completed],['Failed',stats?.failed],['Retry',stats?.retryable]].map(([k,v])=><div className="metric" key={k as string}><span>{k}</span><strong>{v??0}</strong></div>)}</div><h3>Contacts</h3>{contacts.filter(c=>c.phone&&c.status==='ACTIVE'&&!campaignContacts.includes(c.id)).slice(0,50).map(c=><div key={c.id} style={{display:'flex',justifyContent:'space-between',padding:8,borderBottom:'1px solid #ddd'}}><span>{[c.first_name,c.last_name].filter(Boolean).join(' ')||c.phone}</span><button onClick={()=>addContact(c.id)}>Add</button></div>)}<p>Campaign contacts: {campaignContacts.length}</p></>:<p>Select a campaign to manage it.</p>}</div></section></main>
}
