'use client'

import {useEffect,useState} from 'react'

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8001/api/v1'
type Plan={id:string;name:string;limits:Record<string,number>;stripe_price_id:string|null}
type Usage={period_start:string;period_end:string;usage:Record<string,number>;limits:{minutes:number|null;used:number;remaining:number|null}}
export default function BillingPage(){
 const [token,setToken]=useState('');const [plans,setPlans]=useState<Plan[]>([]);const [sub,setSub]=useState<any>(null);const [usage,setUsage]=useState<Usage|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState('')
 useEffect(()=>{setToken(localStorage.getItem('token')||'')},[]);useEffect(()=>{if(token)load()},[token])
 async function api(path:string,options:any={}){const r=await fetch(API+path,{...options,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(options.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||'Request failed');return j}
 async function load(){try{const [p,s,u]=await Promise.all([api('/billing/plans'),api('/billing/subscription'),api('/billing/usage')]);setPlans(p);setSub(s.subscription);setUsage(u)}catch(e:any){setError(e.message)}}
 async function checkout(id:string){try{setBusy(id);const j=await api(`/billing/checkout?plan_id=${encodeURIComponent(id)}`,{method:'POST'});if(j.checkout_url)window.location.href=j.checkout_url}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function portal(){try{setBusy('portal');const j=await api('/billing/portal',{method:'POST'});if(j.portal_url)window.location.href=j.portal_url}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const used=usage?.limits.used??usage?.usage.voice_minutes??0;const limit=usage?.limits.minutes??null;const remaining=usage?.limits.remaining??null;const pct=limit?Math.min(100,used/limit*100):0
 return <main style={{maxWidth:1100,margin:'40px auto',padding:'0 24px'}}><div style={{marginBottom:28}}><div style={{fontSize:12,letterSpacing:2}}>VOICEOS · BILLING</div><h1>Billing & Usage</h1><p>Manage your subscription and monitor monthly voice usage.</p></div>{error&&<div className="card" style={{marginBottom:16}}>{error}</div>}<section className="grid" style={{marginBottom:24}}><div className="metric"><span>Subscription</span><strong>{sub?.status||'Not subscribed'}</strong><small>{sub?.plan||'Choose a plan to enable paid usage.'}</small></div><div className="metric"><span>Voice minutes</span><strong>{used.toFixed(2)}</strong><small>{limit!=null?`${remaining?.toFixed(2)} remaining of ${limit}`:'No configured limit'}</small></div><div className="metric"><span>Billing period</span><strong>{usage?new Date(usage.period_start).toLocaleDateString():'—'}</strong><small>{usage?`through ${new Date(usage.period_end).toLocaleDateString()}`:''}</small></div></section>{limit!=null&&<section className="card" style={{marginBottom:24}}><div style={{display:'flex',justifyContent:'space-between'}}><strong>Monthly voice usage</strong><span>{Math.round(pct)}%</span></div><div style={{height:10,background:'#eee',borderRadius:99,marginTop:12,overflow:'hidden'}}><div style={{height:'100%',width:`${pct}%`,background:'currentColor'}}/></div></section>}{sub?.stripe_customer_id&&<button onClick={portal} disabled={busy==='portal'}>{busy==='portal'?'Opening…':'Manage billing'}</button>}<section style={{marginTop:28}}><h2>Plans</h2><div className="grid">{plans.map(p=><div className="card" key={p.id}><h3>{p.name}</h3><p>{p.limits?.minutes!=null?`${p.limits.minutes} voice minutes / month`:'Custom usage limits'}</p>{p.stripe_price_id?<button onClick={()=>checkout(p.id)} disabled={!!busy}>{busy===p.id?'Opening checkout…':'Choose plan'}</button>:<small>Stripe price not configured</small>}</div>)}</div>{!plans.length&&<div className="card">No billing plans are configured yet.</div>}</section></main>
}
